### ISSUE TITLE
Location of hdf5.h has changed in Debian testing

### ISSUE THREAD

**Issue by quicklisp** [HDFGroup/hdf5-cffi#61]
I'm doing some preliminary build testing on what will become Debian 8. On Debian 7, the libhdf5-dev package installs hdf5.h in /usr/include, but in testing, it's in /usr/include/hdf5/serial/hdf5.h. I'm not sure how you can work with this change, but I wanted to make you aware.

**Comment by liamh** [comment]
I have found that hdf5-cffi will not load in Debian 8 (jessie) unless I rebind `*cc*` and `*foreign-library-directories*`

    (let ((cffi-toolchain:*cc* "/usr/bin/h5cc")
          (cffi:*foreign-library-directories* '("/usr/lib/x86_64-linux-gnu/hdf5/serial/")))
      (ql:quickload "hdf5-cffi"))

**Comment by gheber** [comment]
Where should I add something like that? Of course, the default installation location is different on other systems such as ``/usr/local``, etc.
