### ISSUE TITLE
Building on MacOS X fails

### ISSUE THREAD

**Issue by vseloved** [HDFGroup/hdf5-cffi#62]
I encountered some difficulties building the library on Mac.
The following 2 changes solved the problem for me (however, there may be a better solution).

in `hdf5-cffi.lisp`  istead of `(cffi:use-foreign-library "libhdf5.so")` add:

```lisp
(cffi:define-foreign-library libhdf5
    (:darwin (:default "libhdf5"))
    (t (:default "libhdf5.so")))
  (defun load-hdf5-foreign-libraries ()'
    (cffi:use-foreign-library libhdf5)))
```

in `hdf5/grovel.lisp` add: `(include "sys/time.h")`

**Comment by gheber** [comment]
I just committed your changes. Tested on Debian 7.8. Please try again and confirm!

**Comment by vseloved** [comment]
I think, it won't work without `.so` here: `(t (:default "libhdf5.so")))`

**Comment by gheber** [comment]
Interesting. I thought the (:darwin "...") was for MacOS X? If I add the .so extension to the default (t) condition, it complains that it can't find libhdf5.so.so . Does (:darwin (:default "libhdf5.so")) work for you?

**Comment by vseloved** [comment]
Hm, I see. Seems like your version is correct. (Yes, `:darwin` should go w/o an extension, and ".so" is for Linux-based systems). If you can load on Linux, then it should be ok.
