### ISSUE TITLE
HDF5 v1.10 support

### ISSUE THREAD

**Issue by liamh** [HDFGroup/hdf5-cffi#64]
Debian testing has v1.10 of the HDF5 library. When I try to run my application that works on v1.8, it produces a broken HDF5 file that is not readable even by h5ls or h5dump. I am not attempting to use, nor do I need, any of the features added in v1.10; I am simply trying to run the code that works with v1.8.
Is there any reason why hdf5-cffi will not work with v1.10 of the library?

**Comment by gheber** [comment]
I haven't tried that (will do over the weekend!), but I don't see a reason why it shouldn't work. The only "breaking change" in 1.10 is that `hid_t` is now a 64-bit integer type. But that comes straight from `H5Ipublic.h` into `h5i-grovel.lisp` and should be fine.

**Comment by gheber** [comment]
Two "breaking" changes in 1.10:

1. `H5Rdereference` prototype changed
2. `H5Fget_info` prototype changed

No problems otherwise. Will fix.
