### ISSUE TITLE
error on loading with sbcl 1.4 osx

### ISSUE THREAD

**Issue by jccerrillo** [HDFGroup/hdf5-cffi#68]
Compiling is ok with ccl but fails with sbcl
this is the error:

7 warnings generated.
; clang -o /Users/jc/.cache/common-lisp/sbcl-1.4.0-macosx-x64/Users/jc/quicklisp/local-projects/hdf5-cffi/hdf5/h5f-grovel__grovel-tmpAAURSO1 -g -mmacosx-version-min=10.6 -Wl,-no_pie -arch x86_64 -dynamic -twolevel_namespace -bind_at_load -pagezero_size 0x100000 /Users/jc/.cache/common-lisp/sbcl-1.4.0-macosx-x64/Users/jc/quicklisp/local-projects/hdf5-cffi/hdf5/h5f-grovel__grovel.o

Undefined symbols for architecture x86_64:
  "_H5check_version", referenced from:
      _main in h5f-grovel__grovel.o
  "_H5open", referenced from:
      _main in h5f-grovel__grovel.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
While evaluating the form starting at line 2, column 0
  of #P"/Users/jc/quicklisp/local-projects/hdf5-cffi/make-hdf5.lisp":

debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {1001937003}>: Subprocess (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>)
 with command ("clang" "-o" "/Users/jc/.cache/common-lisp/sbcl-1.4.0-macosx-x64/Users/jc/quicklisp/local-projects/hdf5-cffi/hdf5/h5f-grovel__grovel-tmpAAURSO1" "-g" "-mmacosx-version-min=10.6" "-Wl,-no_pie" "-arch" "x86_64" "-dynamic" "-twolevel_namespace" "-bind_at_load" "-pagezero_size" ...)
 exited with error code 1

**Comment by guicho271828** [comment]
the current master did not work for me too. I'm not a maintainer, but could you try this branch?
https://github.com/HDFGroup/hdf5-cffi/pull/67

**Comment by jccerrillo** [comment]
had to change the library defaul path as Hombrew installs in /usr/local/Cellar/hdf5/...
but still had no luck

Subprocess (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>)
 with command ("clang" "-o"
               ".../hdf5-cffi/hdf5/h5f-grovel__grovel-tmpAAURSO1"
               "-g" "-mmacosx-version-min=10.6" "-Wl,-no_pie"
               "-arch" "x86_64" "-dynamic" "-twolevel_namespace"
               "-bind_at_load" "-pagezero_size" "0x100000"
               ".../quicklisp/local-projects/hdf5-cffi/hdf5/h5f-grovel__grovel.o")
 exited with error code 1

**Comment by jccerrillo** [comment]
Ah, I was on the wrong branch! It works fine. Many thanks.

**Comment by guicho271828** [comment]
Good to hear that my branch worked on OSX. I don't have the environment.
Could you try running the test suite? `(asdf:test-system :hdf5-cffi)`.

**Comment by guicho271828** [comment]
btw it should show 4 failures at the moment. I do not know how the original examples run correctly.

**Comment by jccerrillo** [comment]
tests output is:

 Did 63 checks.
    Pass: 59 (93%)
    Skip: 0 ( 0%)
    Fail: 4 ( 6%)

 Failure Details:
 --------------------------------
 GROUPS []: 
      While running test examples/groups/h5ex-g-iterate.lisp:
  Invalid handle found..
 --------------------------------
 --------------------------------
 GROUPS []: 
      While running test examples/groups/h5ex-g-traverse.lisp:
  Invalid handle found..
 --------------------------------
 --------------------------------
 GROUPS []: 
      While running test examples/groups/h5ex-g-visit.lisp:
  Component HDF5-EXAMPLES not found.
 --------------------------------
 --------------------------------
 BASICS []: 
      While running test examples/basics/h5-cmprss.lisp:
  Invalid handle found..
 --------------------------------

**Comment by guicho271828** [comment]
now the 4 errors are fixed. see comments #67
